# Generated by Django 4.2.10 on 2025-04-22 13:45

from django.db import migrations, models
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="File ID",
                    ),
                ),
                (
                    "original_file_name",
                    models.CharField(max_length=255, verbose_name="Original File Name"),
                ),
                (
                    "user_defined_file_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="User Defined File Name",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=files.models.file_upload_path, verbose_name="File"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "File",
                "verbose_name_plural": "Files",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
